title: Esantomi
description: >-
  Esan&#39;s github blog <br>
  with portfolio.
url: "https://esantomi.github.io"
github: Esantomi
email: deomi@knou.ac.kr
google_analytics: <YOUR UA TOKEN>

exclude: [README.md, Gemfile, Gemfile.lock]

comments:
  enabled: true
  repo: Esantomi/Esantomi.github.io
  issue-term: pathname
  theme: github-light

collections:
  pages:
    output: true
  projects:
    output: true
  tags:
    output: true

defaults:
  - scope:
      type: pages
    values:
      layout: default
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title
  - scope:
      type: projects
    values:
      layout: project
      permalink: /projects/:title
  - scope:
      type: tags
    values:
      layout: tag
      permalink: /tags/:title
